In [110]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

import pickle
with open('/home/ema/dev/shocks/data/processed/AVAXBTC_1h.pkl', 'rb') as f:
    d = pickle.load(f)

d["features"]
data = [el for el in d["features"] if el["direction"] != 0]
non_shocks = [el for el in d["features"] if el["direction"] == 0]
data.extend(non_shocks[: 2 * len(data)])

binary = True
if binary:
    for el in data:
         direction = el['direction']
         el['direction'] = 1 if direction == -1 else direction

df = pd.DataFrame.from_dict(data).dropna()
cols = [col for col in df.columns if col != 'direction']
labels = df['direction'].tolist()
X_train, X_test, y_train, y_test = train_test_split(df[cols], labels, test_size=0.3, random_state=42, stratify=labels)


In [117]:
d["data"]

close    volume   returns  log_returns     alpha  \
open time                                                                  
2021-10-11 09:00:00  0.001031  10849.86 -0.014157    -0.014258  1.596212   
2021-10-11 10:00:00  0.001022  15932.58 -0.008054    -0.008086  1.694612   
2021-10-11 11:00:00  0.001019  13312.57 -0.003130    -0.003135  1.694619   
2021-10-11 12:00:00  0.001021   5962.94  0.002257     0.002254  1.694609   
2021-10-11 13:00:00  0.000997  23196.41 -0.024280    -0.024580  1.596759   
...                       ...       ...       ...          ...       ...   
2022-03-31 19:00:00  0.002073   8011.64 -0.010029    -0.010079  1.478796   
2022-03-31 20:00:00  0.002089   4698.69  0.007670     0.007641  1.478796   
2022-03-31 21:00:00  0.002097   2296.89  0.003734     0.003727  1.478361   
2022-03-31 22:00:00  0.002109   5709.03  0.006105     0.006086  1.479089   
2022-03-31 23:00:00  0.002141   6795.20  0.014695     0.014588  1.470149   

                         beta     sigma      mu_0      mu_1  
open time                                                    
2021-10-11 09:00:00 -0.127735  0.004948 -0.001687 -0.002152  
2021-10-11 10:00:00  0.042426  0.004951 -0.001583 -0.001473  
2021-10-11 11:00:00  0.062868  0.004951 -0.001672 -0.001510  
2021-10-11 12:00:00  0.033923  0.004952 -0.001545 -0.001458  
2021-10-11 13:00:00 -0.133617  0.004951 -0.001664 -0.002150  
...                       ...       ...       ...       ...  
2022-03-31 19:00:00  0.023961  0.004479 -0.000390 -0.000275  
2022-03-31 20:00:00  0.023961  0.004479 -0.000390 -0.000275  
2022-03-31 21:00:00  0.006235  0.004480 -0.000241 -0.000211  
2022-03-31 22:00:00  0.006211  0.004484 -0.000241 -0.000211  
2022-03-31 23:00:00  0.030921  0.004521 -0.000192 -0.000038  

[4119 rows x 9 columns]

In [34]:
class_weights = {
   #-1: (len([el for el in labels if el == -1]) / len(labels)),
    0: (len([el for el in labels if el == 0]) / len(labels)),
    1: (len([el for el in labels if el == 1]) / len(labels)),
}

model = RandomForestClassifier(class_weight=class_weights)
model.fit(X_train, y_train)
preds = model.predict(X_test)
print(classification_report(y_test, preds, target_names=['0', '1']))

              precision    recall  f1-score   support

           0       0.72      0.82      0.77       211
           1       0.49      0.34      0.40       105

    accuracy                           0.66       316
   macro avg       0.60      0.58      0.59       316
weighted avg       0.64      0.66      0.65       316



In [35]:
from sklearn.dummy import DummyClassifier

model = DummyClassifier(strategy="uniform")
model.fit(X_train, y_train)
preds = model.predict(X_test)
print(classification_report(y_test, preds, target_names=['0', '1']))

              precision    recall  f1-score   support

           0       0.66      0.51      0.57       211
           1       0.32      0.48      0.39       105

    accuracy                           0.50       316
   macro avg       0.49      0.49      0.48       316
weighted avg       0.55      0.50      0.51       316



In [12]:
import pickle
with open('/home/ema/dev/shocks/data/processed/AVAXBTC_5m.pkl', 'rb') as f:
    d = pickle.load(f)
data3 = [el for el in d["features"] if el["direction"] != 0]
non_shocks = [el for el in d["features"] if el["direction"] == 0]
data3.extend(non_shocks[:len(data3)])

df = pd.DataFrame.from_dict(data3).dropna()
cols = [col for col in df.columns if col != 'direction']
labels = df['direction'].tolist()
X_train, X_test, y_train, y_test = train_test_split(df[cols], labels, test_size=0.3, random_state=42, stratify=labels)

In [17]:
class_weights = {
   -1: (len([el for el in labels if el == -1]) / len(labels)),
    0: (len([el for el in labels if el == 0]) / len(labels)),
    1: (len([el for el in labels if el == 1]) / len(labels)),
}

model = RandomForestClassifier(class_weight=class_weights)
model.fit(X_train, y_train)
preds = model.predict(X_test)
print(classification_report(y_test, preds, target_names=['-1', '0', '1']))

              precision    recall  f1-score   support

          -1       0.50      0.05      0.09        42
           0       0.56      0.82      0.67       106
           1       0.50      0.41      0.45        63

    accuracy                           0.55       211
   macro avg       0.52      0.43      0.40       211
weighted avg       0.53      0.55      0.49       211



In [16]:
from sklearn.dummy import DummyClassifier

model = DummyClassifier(strategy="uniform")
model.fit(X_train, y_train)
preds = model.predict(X_test)
print(classification_report(y_test, preds, target_names=['-1', '0', '1']))

              precision    recall  f1-score   support

          -1       0.21      0.33      0.25        42
           0       0.48      0.32      0.38       106
           1       0.28      0.32      0.30        63

    accuracy                           0.32       211
   macro avg       0.32      0.32      0.31       211
weighted avg       0.36      0.32      0.33       211



In [2]:
import pystable
from numpy.lib.stride_tricks import sliding_window_view

data = d["data"][["close"]].iloc[: 1000]
np_data = np.array(data["close"].tolist())


init_fit = {"alpha": 2, "beta": 0, "sigma": 1, "mu": 0, "parameterization": 1}
dist = pystable.create(
    init_fit["alpha"],
    init_fit["beta"],
    init_fit["sigma"],
    init_fit["mu"],
    init_fit["parameterization"],
)

def fit(data, dist, params=("alpha", "beta")):
    for param in params:
        data[param] = (
            data["close"]
            .rolling(250)
            .apply(lambda x: fit_levy(x, dist))
        )
    return data


def fit_levy(log_returns, dist):
    pystable.fit(dist, log_returns, len(log_returns))
    return dist.contents.alpha

In [3]:
%%time
fitted = fit(data, dist, ["alpha"])

CPU times: user 44.8 s, sys: 1.14 s, total: 46 s
Wall time: 20.5 s


In [74]:
%%time

for _ in range(10000):
    init_fit = {"alpha": 2, "beta": 0, "sigma": 1, "mu": 0, "parameterization": 1}
    dist = pystable.create(
        init_fit["alpha"],
        init_fit["beta"],
        init_fit["sigma"],
        init_fit["mu"],
        init_fit["parameterization"],
    )

CPU times: user 2.4 s, sys: 361 ms, total: 2.76 s
Wall time: 2.79 s


In [5]:
window_view = sliding_window_view(np.array(np_data), window_shape=250)


In [6]:
%%time
a = list(map(lambda x: fit_levy(x, dist), window_view))

CPU times: user 44.3 s, sys: 821 ms, total: 45.1 s
Wall time: 16.3 s


In [45]:
from concurrent import futures
import multiprocessing
pool = multiprocessing.Pool(processes=8)

def _fit_levy(log_returns):
    pystable.fit(dist, log_returns, len(log_returns))
    return np.array([dist.contents.alpha, 1])

In [77]:
%%time
def _fit_levy(log_returns):
    init_fit = {"alpha": 2, "beta": 0, "sigma": 1, "mu": 0, "parameterization": 1}
    dist = pystable.create(
        init_fit["alpha"],
        init_fit["beta"],
        init_fit["sigma"],
        init_fit["mu"],
        init_fit["parameterization"],
    )
    pystable.fit(dist, log_returns, len(log_returns))
    return np.array([dist.contents.alpha, dist.contents.beta])
    
with futures.ProcessPoolExecutor(max_workers=4) as executor:
    res = executor.map(_fit_levy, window_view)
    #futs = [executor.submit(fit_levy, window_view, ) for _ in range(8)]
#list(res)
#results = [f.result() for f in futs]
np.array(list(res))

CPU times: user 390 ms, sys: 122 ms, total: 512 ms
Wall time: 14.9 s


array([[0.65086957, 0.61655576],
       [0.64665547, 0.61723967],
       [0.64599075, 0.61733951],
       ...,
       [1.96201399, 0.02192405],
       [1.96201399, 0.02192405],
       [1.96201399, 0.02192405]])

In [108]:
f = np.array(a)[:, 0]
nans = [np.nan] * 249
np.concatenate([nans, f])

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [76]:
%%time
pool = multiprocessing.Pool(processes=4)

def _fit_levy(log_returns):
    init_fit = {"alpha": 2, "beta": 0, "sigma": 1, "mu": 0, "parameterization": 1}
    dist = pystable.create(
        init_fit["alpha"],
        init_fit["beta"],
        init_fit["sigma"],
        init_fit["mu"],
        init_fit["parameterization"],
    )
    pystable.fit(dist, log_returns, len(log_returns))
    return np.array([dist.contents.alpha, dist.contents.beta])

a = pool.map(_fit_levy, window_view)

CPU times: user 70.5 ms, sys: 103 ms, total: 173 ms
Wall time: 14.7 s


In [54]:
np.array(a)

array([[0.65086957, 0.65086957],
       [0.64665547, 0.64665547],
       [0.64599075, 0.64599075],
       ...,
       [1.96201399, 1.96201399],
       [1.96201399, 1.96201399],
       [1.96201399, 1.96201399]])

In [20]:
fitted.iloc[249], data.loc["2021-10-02 17:35:00"]

(close    0.00151
 alpha    0.65087
 Name: 2021-10-02 17:35:00, dtype: float64,
 close    0.00151
 alpha    0.65087
 Name: 2021-10-02 17:35:00, dtype: float64)

In [29]:
c["alpha"] = np.nan
c = data.copy()

In [30]:
window = 250
c["alpha"] = [np.nan] * (window - 1) + fitted.iloc[window - 1: ]["alpha"].tolist()

In [32]:
fitted.iloc[-1], data.iloc[-1]

(close    0.001326
 alpha    1.962014
 Name: 2021-10-05 08:05:00, dtype: float64,
 close    0.001326
 alpha    1.962014
 Name: 2021-10-05 08:05:00, dtype: float64)